[package]
name = "xdp-prog"
version = "0.1.0"
edition = "2021"
[dependencies]
aya-bpf = "0.1.0"
aya-log-ebpf = "0.1.0"
common = { path = "../common" }
network-types = "0.0.1"
[[bin]]
name = "xdp-prog"
path = "src/main.rs"